Httpclient java11 and 20.12 french translation (#36)
* WIP Using the Java 11 HttpClient

* TODO

* No need for the Apache HttpClient libraries

* Weather retriever with new Http Client

* Adding the weather unit tests

* Dropbox actuallty requires the apache http library(ies)
ava.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at com.github.fge.fs.dropbox.driver.DropBoxFileSystemDriver.newWatchService(DropBoxFileSystemDriver.java:426)

* TODO

* Revert

* TODO

* Using the Java 11 http client

* Revert

* French translation

* Revert

* Misc