[Pref Page Navigation] Fixed NPE
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.custom.CTabFolder.setSelection(int)" because "this._tabFolder" is null
	at net.tourbook.preferences.PrefPageComputedValues.applyData(PrefPageComputedValues.java:166)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.createPage(FilteredPreferenceDialog.java:345)