[2.5 Map] Code cleanup, map it is now working for off/online maps but it causes errors when the - map provider - theme - style are switched too fast (when the previous is not fully loaded)
Caused errors

1. "[TileLoader0] ERROR MapDatabase - null", this is a "java.nio.channels.ClosedChannelException"

2. WARNING: DiskLruCache C:\CACHE\vtm-tile-cache is corrupt: failed to rename C:\CACHE\vtm-tile-cache\journal to C:\CACHE\vtm-tile-cache\journal.bkp, removing
java.io.IOException: failed to rename C:\CACHE\vtm-tile-cache\journal to C:\CACHE\vtm-tile-cache\journal.bkp
	at okhttp3.internal.io.FileSystem$1.rename(FileSystem.java:85)

   Can be fixed when closing MT and deleting all cached files