fixed sql error
!MESSAGE ALTER TABLE TOURDATA   ADD COLUMN surfing_IsMinDistance BOOLEAN
DEFAULT false

!ENTRY net.tourbook.common 4 0 2018-12-12 08:52:15.830
!MESSAGE SQLException

SQLState: XCL47
ErrorCode: 30000
Message: Use of 'BOOLEAN' requires database to be upgraded from version
10.5 to version 10.7 or later.
java.sql.SQLException: Use of 'BOOLEAN' requires database to be upgraded
from version 10.5 to version 10.7 or later.