[Database] Fixed default value. The default value in the db was 0 but adding the column wanted to set the default value to null
This should not affect normal users because this issue occurred when updating db version 52 -> 54

06:54:37.797[Splash message] Data update 54  ·  1874 of 4639  ·  40.4 %  ·  88 Δ
06:54:38,037  INFO DefaultLoadEventListener:134 - Error performing load command

org.hibernate.PropertyAccessException: Null value was assigned to a property of primitive type setter of net.tourbook.data.TourLocation.lastModified

	at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:106)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.setPropertyValues(AbstractEntityTuplizer.java:352)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.setPropertyValues(PojoEntityTuplizer.java:232)

...

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

Caused by: java.lang.IllegalArgumentException: Can not set long field net.tourbook.data.TourLocation.lastModified to null value

	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at java.base/jdk.internal.reflect.UnsafeLongFieldAccessorImpl.set(UnsafeLongFieldAccessorImpl.java:80)
	at java.base/java.lang.reflect.Field.set(Field.java:799)
	at org.hibernate.property.DirectPropertyAccessor$DirectSetter.set(DirectPropertyAccessor.java:102)
	... 43 more
06:54:38,038  INFO DefaultLoadEventListener:134 - Error performing load command