[Photos + Tours] Fixed NPE
java.lang.NullPointerException: Cannot read field "mapPoint" because "this._hoveredMapPoint" is null
        at net.tourbook.map2.view.MapPointToolTip.createUI(MapPointToolTip.java:126)
        at net.tourbook.map2.view.MapPointToolTip.createToolTipContentArea(MapPointToolTip.java:117)
        at net.tourbook.common.util.ToolTip.toolTipShow(ToolTip.java:872)
        at net.tourbook.common.util.ToolTip.lambda$1(ToolTip.java:847)