java.lang.NullPointerException: Cannot invoke "java.lang.Float.longValue()" because the return value of "com.garmin.fit.LapMesg.getTotalElapsedTime()" is null 	at net.tourbook.device.garmin.fit.listeners.MesgListener_Lap.setMarker(MesgListener_Lap.java:80)