fixed issue that the column manager dialog could not be opened in ...
a slideout, this caused a

java.lang.IllegalArgumentException: Widget has the wrong parent

it's highly complicated with the reparented shell but finally it worked
(on windows)