Adding the ability to upload tours to Strava (#266)
* Fix for GPX tests

* Fix as using assert doesn't work but the JUnit 5 asserts work

* Setting a different order so that the tests is sure to fail until I find
a way to ignore the tour markers array items order

* Using JSONUnit as it looks more robust and flexible

* Maybe we should go back to xml...

* Trying to use XML but not much success

* Now blocked with this javax.xml.bind.JAXBException: ClassCastException:
attempting to cast
bundleresource://61.fwk769858312:2/javax/xml/bind/JAXBContext.class to
bundleresource:

* Revert "Now blocked with this javax.xml.bind.JAXBException: ClassCastException: attempting to cast bundleresource://61.fwk769858312:2/javax/xml/bind/JAXBContext.class to bundleresource:"

This reverts commit 49e6c2da6312c3e556ef0cb4537f6e4069bce6df.

* Revert "Trying to use XML but not much success"

This reverts commit 2e0ad1c65cbd8ef47ebefb718904987542891340.

* Revert "Maybe we should go back to xml..."

This reverts commit fd22f3a22a42b0aba7b0b8c05cd1818d7cd19de8.

* Revert "Using JSONUnit as it looks more robust and flexible"

This reverts commit 9cf8462f11f6cedfebed5daf727c952f7dbe05c6.

* Using the sorted tour markers instead of the set that can have random
order

* Removing the JsonIgnore from TourData and ignoring the appropriate
properties in the tests instead. Library updates

* Removing code smells for more efficiency ( The time complexity of any
isEmpty() method implementation should be O(1) whereas some
implementations of size() can be O(n).)

* Method names should always start with lowercase

* Package updates

* Comment

* Suunto9: Pauses less than 1sec should not be imported

* When computing the cadence zone times, we prevent from re-importing the
last imported tours

* Displyaing the errors when the tests fail

* Replacing .size() == 0 with .isEmpty() and .size() < 1 with .isEmpty()

* Replacing .size() > 0 with .isEmpty() == false

* Replacing .size() <= 0 with .isEmpty()

* French translation

* Misc

* Using net.tourbook.common.ui

* TourMarker View bugfix : The time difference, average pace and average
speed between markers could be wrong in the case of multiple selected
tours

* Misc

* Worldwind 2.2.0 Update (#29)

* Added the WoldWind jars I built locally with the develop branch from
today (Need JRE 11)

* Misc

* Updating to the official Worldwind 2.2

* Spaces

* Clean up

* Clean up

* MANIFEST updates

* Clean up and warning removals

* Build fix and validation

* Adding the WorldWind commit id

* Misc

* Readme

* Using the Java 11 feature Files.readString

* Removing unused parameters and misc

* Bugfix: Printing a tour when using Java11 is resulting in exceptions

* Adding the istack commons runtime library

* Activation library

* Resolving the JAXB NPE  java.util.List is an interface, and JAXB can't
handle interfaces

* WIP Resolving the exception : unable to marshal type
"net.tourbook.data.TourData" as an element because it is missing an
@XmlRootElement annotation

* WIP Resolving Caused by: com.sun.istack.SAXException2: A cycle is
detected in the object graph. This will cause infinitely deep XML:

* That seems to have it resolved

* Spaces

* That fixed it!

* Printing libraries

* WIP

* FIXED!

* MVN urls

* Not needed

* Misc

* Not needed

* Reverting

* Misc and reverts

* Misc

* Not useful as this string is only used in the XSL transform

* Not needed

* Markers not tags

* Readme update

* Typo

* Code improvements

* More readable code

* Merge part2

* French translation

* Httpclient java11 and 20.12 french translation (#36)

* WIP Using the Java 11 HttpClient

* TODO

* No need for the Apache HttpClient libraries

* Weather retriever with new Http Client

* Adding the weather unit tests

* Dropbox actuallty requires the apache http library(ies)
ava.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at com.github.fge.fs.dropbox.driver.DropBoxFileSystemDriver.newWatchService(DropBoxFileSystemDriver.java:426)

* TODO

* Revert

* TODO

* Using the Java 11 http client

* Revert

* French translation

* Revert

* Misc

* Updating the GeoCompareView when the measurement system has changed

* French translation

* French translation

* French translation

* Misc code changes

* Revert

* Revert

* Adding the ability to upload tours to Strava (#37)

* Retrieving the access and refresh token from Strava

* Creating the CloudUploader extentions to be used in the TourbookView
"Upload" contextual menu

* The Strava Uploader is found and its uploadTours function is triggered

* Misc progress

* WIP Trying to upload a file from the desktop to strava

* Trying to upload a file to Strava and troubleshooting why the connect
button is not fully displayed

* Fix for the connect button not fully displayed

* UI WIP

* WIP

* WIP

* Uploading a file to Strava for the first time from MT!

* Retrieving the actual created activity id

* WIP

* WIP

* WIP Preference page

* Nice UI. Performed tests

* WIP Adding the ExpireAt data

* Beautify

* BIG WIP Extracting the code to generate a TCX file from a tour

* The upload of a tour to strava works! (Bug to fix : Velocity NPE)

* Rearrangement

* Misc

* WIP Refreshing the token if necessary

* The refresh of a token works!

* WIp Velocity

* Velocity now working (not sure as it was not working on Windows earlier)

* Trying to make a link clickable from the log viewer. It works but it
opens the web page inside the log viewer

* Misc

* Polishing the extraction of the TCX and GPX export code

* More

* Lots of progress for today!

* More progress

* WIP

* Better UI

* Done!

* WIP TCX unit tests

* MIsc

* Typo

* Control files TOREDO as they were done with this modified code but
should be done with the official 20.12

* Fix for sending the activity type when

* Unit tests 100% successful

* Adding the GPX tester. Unit tests 100% successful. Now I need to add the
remaining tests cases for Export GPX and TCX. Ya plus qu'a!

* Forgotten file

* Todo

* Fix

* Changing the Heroku app URL

* Renaming

* Centering the button

* Readme

* Revert

* Misc

* Not needed

* All Options generated with 20.12

* Unit test files generated with 20.12

* WIP Unit tests

* Misc

* Fixed

* Externalizing

* Reorganization of the authorizatio and token retrieval

* Fix the velocity issue

* arg

* Possible fix

* Updating to Velocity 2.0

* Libraries

* Fix for refreshing tokens

* Fixes

* Unit tests

* Unit tests progress : 3 to fix

* Making them generic.

* Unit test fixes

* Unit tests 100% successful!

* PR link

* French translation

* Misc