[SQL] Fixed SQLSyntaxErrorException
After many weeks ob developing without any problems, suddenly there is a sql exception. Today I replaced the sql database with my production, but this should not be the reason. Very strange :-(

!MESSAGE A problem occurred while trying to acquire a cached PreparedStatement in a background thread.
!STACK 0
java.sql.SQLSyntaxErrorException: Lexical error at line 20, column 0.  Encountered: <EOF> after : "".
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)